### ISSUE TITLE
Linux Version

### ISSUE THREAD

**Issue by GuestSneezeOSDev** [nir9/lightwm#16]

**Comment by AFellowSpeedrunner** [comment]
There are already good alternatives like i3 and BSPWM on Linux which are all like it but lightwm is built to work with the window restrictions and limitations that Windows imposes and attempts to bring a similar experience to Windows.

I highly doubt that Nir would port this to Linux considering how many WM's already exist and the work that would be needed would be similar to making a desktop environment/window manager from scratch to support both Xorg and Wayland. 

It'd be cool to see lightwm in Linux as it's own environment but I don't see it happening due to the projects minimalistic approach, current Windows-only nature and that there are better alternatives on Linux that aren't limited by the same limits Windows has.

Perhaps someone will probably bring it to Linux themselves but I don't expect Nir himself to port it as he wrote this for Windows originally and not the Linux kernel.

**Comment by nir9** [comment]
@AFellowSpeedrunner +1

My fav on X11 is dwm

**Comment by AFellowSpeedrunner** [comment]
> @AFellowSpeedrunner +1
> 
> My fav on X11 is dwm

I personally use i3 X11 on a Chromebook that I put Gentoo on. It works with 16GB of storage... barely.

**Comment by GuestSneezeOSDev** [comment]
I use Arch Linux btw

**Comment by AFellowSpeedrunner** [comment]
> I use Arch Linux btw

I switch between Gentoo, Arch, and Ubuntu on multiple drives or computers. Gentoo for my Chromebook, Arch and Ubuntu on two drives for my main machine but I use Windows as my main OS usually.
