### ISSUE TITLE
Add an outline to the window in focus.

### ISSUE THREAD

**Issue by irivia** [nir9/lightwm#19]
At first I wanted to try implementing this myself but whenever I try to compile the program it gives me this error:

tiling.obj : error LNK2019: unresolved external symbol __imp_CreateSolidBrush referenced in function focusNextWindow
tiling.obj : error LNK2019: unresolved external symbol __imp_Rectangle referenced in function focusNextWindow
tiling.obj : error LNK2019: unresolved external symbol __imp_SelectObject referenced in function focusNextWindow
debug\lightwm.exe : fatal error LNK1120: 3 unresolved externals
NMAKE : fatal error U1077: 'cl /DDEBUG /Zi /W3 wm.c tiling.c error.c keyboard.c shared_mem.c /link kernel32.lib user32.lib /out:debug/lightwm.exe /subsystem:windows /entry:wWinMain' : return code '0x2'
Stop.

**Comment by nir9** [comment]
The linker errors occur since you are using functions from gdi32.dll but you forgot to add gdi32.lib to the linker parameters (in the makefile), so the linker can't find the function being used.From: Alucard ***@***.***>Sent: Sunday, September 1, 2024 2:17:59 AMTo: nir9/lightwm ***@***.***>Cc: Subscribed ***@***.***>Subject: [nir9/lightwm] Add an outline to the window in focus (Issue #19)
At first I wanted to try implementing this myself but whenever I try to compile the program it gives me this error:
tiling.obj : error LNK2019: unresolved external symbol __imp_CreateSolidBrush referenced in function focusNextWindow
tiling.obj : error LNK2019: unresolved external symbol __imp_Rectangle referenced in function focusNextWindow
tiling.obj : error LNK2019: unresolved external symbol __imp_SelectObject referenced in function focusNextWindow
debug\lightwm.exe : fatal error LNK1120: 3 unresolved externals
NMAKE : fatal error U1077: 'cl /DDEBUG /Zi /W3 wm.c tiling.c error.c keyboard.c shared_mem.c /link kernel32.lib user32.lib /out:debug/lightwm.exe /subsystem:windows /entry:wWinMain' : return code '0x2'
Stop.

**Comment by irivia** [comment]
The issue is fixed, thanks!
