### ISSUE TITLE
ADD A BAR

### ISSUE THREAD

**Issue by muzaffar1337** [nir9/lightwm#21]
ADD A BAR to let us now in which workspace we are also and a title for the current window

**Comment by IAmTheNerdNextDoor** [comment]
Hello, I'm the person who added the workspace switcher code. (not workspaces entirely, just the code to move windows between the workspaces since it wasn't implemented yet originally)

It would be a good idea to add a bar in but it would be impossible. Adding a bar that cannot be moved in Windows.h would be annoying and would be hard to get working right along with tracking the workspace the enduser is in. 

As well, Windows already has a non-movable taskbar at the bottom. We are working with Windows restrictions here, we can't just remove the taskbar without getting rid of explorer which would be a huge problem. 

I must also mention that adding a bar at the top wouldn't look great in my opinion. Putting it at the bottom would be nicer, but as I've said that wouldn't be possible due to explorer limits in Windows with the pre-existing taskbar.

I really don't see a point to this also taking into consideration the very minimalistic approach that nir9 took to make this project. I do think your idea is good but with what this project is, the work this would take and the minimalistics, it's not worth it.

Taken from README:

> One of my main goals with this project is to keep it as minimal as possible, for example I decided against using a dynamic configuration on purpose.

> Also notice that this project does not use any C library functions on purpose, only Windows API. This keeps everything as minimal as possible.

Windows API meaning Windows.h and calls in Windows, but if you are so inclined to have a workspace bar in LightWM, I do suggest you clone this repo and add it yourself.

**Comment by mudhafarx** [comment]
Thanks for your awesome reply, and thank you guys for this project. I really love it and started using it because I was an i3wm user. I was trying to add a small bar or a number that tells me which workspace I'm in, but unfortunately, I'm not that good at C programming.

**Comment by IAmTheNerdNextDoor** [comment]
> Thanks for your awesome reply, and thank you guys for this project. I really love it and started using it because I was an i3wm user. I was trying to add a small bar or a number that tells me which workspace I'm in, but unfortunately, I'm not that good at C programming.

Thanks for understanding! I actually am a i3wm user on my Gentoo Chromebook funnily enough. I use Polybar instead of i3bar though.

**Comment by mudhafarx** [comment]
> > Thanks for your awesome reply, and thank you guys for this project. I really love it and started using it because I was an i3wm user. I was trying to add a small bar or a number that tells me which workspace I'm in, but unfortunately, I'm not that good at C programming.
> 
> Thanks for understanding! I actually am a i3wm user on my Gentoo Chromebook funnily enough. I use Polybar instead of i3bar though.

i was used it in arch also using polybar

**Comment by IAmTheNerdNextDoor** [comment]
> > > Thanks for your awesome reply, and thank you guys for this project. I really love it and started using it because I was an i3wm user. I was trying to add a small bar or a number that tells me which workspace I'm in, but unfortunately, I'm not that good at C programming.
> > 
> > 
> > Thanks for understanding! I actually am a i3wm user on my Gentoo Chromebook funnily enough. I use Polybar instead of i3bar though.
> 
> i was used it in arch also using polybar

I used Arch too, it's pretty good honestly but there I only used i3bar.

**Comment by nir9** [comment]
+1 on what @AFellowSpeedrunner said, although I will add that hiding the taskbar is easily possible since it is just a matter of getting the handle of the taskbar window and hiding it (other projects like dwm-win32 take this approach, and also have an upper bar in a similar fashion that exists in dwm/i3).

Coming from dwm-win32 which I used previously for a couple of years, I have decided after encountering various bugs which were hard to pin down, to make a new window manager from scratch with a different approach than what a lot of the other Win32 ones have, in which the idea here is to focus on stability, minimalism and blending in with the Windows environment as much as possible.

@muzaffar1337 I do agree that it's a good idea to add some visible indication at least showing the current active workspace, perhaps maybe in the tray section, or maybe indeed a small overlay, still thinking about it, open for ideas :)

**Comment by mudhafarx** [comment]
> +1 on what @AFellowSpeedrunner said, although I will add that hiding the taskbar is easily possible since it is just a matter of getting the handle of the taskbar window and hiding it (other projects like dwm-win32 take this approach, and also have an upper bar in a similar fashion that exists in dwm/i3).
> 
> Coming from dwm-win32 which I used previously for a couple of years, I have decided after encountering various bugs which were hard to pin down, to make a new window manager from scratch with a different approach than what a lot of the other Win32 ones have, in which the idea here is to focus on stability, minimalism and blending in with the Windows environment as much as possible.
> 
> @muzaffar1337 I do agree that it's a good idea to add some visible indication at least showing the current active workspace, perhaps maybe in the tray section, or maybe indeed a small overlay, still thinking about it, open for ideas :)

I'm really excited to try out more of these ideas. Thank you so much! Also, showing the current workspace number in the tray section is a great idea

**Comment by IAmTheNerdNextDoor** [comment]
> +1 on what @AFellowSpeedrunner said, although I will add that hiding the taskbar is easily possible since it is just a matter of getting the handle of the taskbar window and hiding it (other projects like dwm-win32 take this approach, and also have an upper bar in a similar fashion that exists in dwm/i3).
> 
> 
> 
> Coming from dwm-win32 which I used previously for a couple of years, I have decided after encountering various bugs which were hard to pin down, to make a new window manager from scratch with a different approach than what a lot of the other Win32 ones have, in which the idea here is to focus on stability, minimalism and blending in with the Windows environment as much as possible.
> 
> 
> 
> @muzaffar1337 I do agree that it's a good idea to add some visible indication at least showing the current active workspace, perhaps maybe in the tray section, or maybe indeed a small overlay, still thinking about it, open for ideas :)

I do agree with @nir9 on this one. I didn't know that you could hide the taskbar like that though. Guess you learn something new everyday. 

I do think this may be possible in another form, maybe like a key combo to show the number of the current workspace on screen for 3 seconds before disappearing.

**Comment by nir9** [comment]
@AFellowSpeedrunner Nice, the key combo is a good idea!

**Comment by nir9** [comment]
Maybe the key combo could also show what windows are in each workspace to help get a general picture

**Comment by IAmTheNerdNextDoor** [comment]
> @AFellowSpeedrunner Nice, the key combo is a good idea!

Thanks @nir9!

> Maybe the key combo could also show what windows are in each workspace to help get a general picture

I actually really like that idea, that would help minimise confusion. It could give a list of what windows are in what workspace.
