### ISSUE TITLE
doesn't work on Windows 11

### ISSUE THREAD

**Issue by polatengin** [nir9/lightwm#4]
I watched your Youtube video, thanks for that 👍

I tried to do the same on my local environment.

I wrote both of the C files, compiled the code and ran the linker to have one exe and one dll files.

I'm having the same files as you, after `cl` and `link` commands

When I run the `wm.exe` it just wait and I don't see it arranges the windows as they created.

Just to double check if I made a mistake when I'm writing the C files, I cloned this repo, used `nmake all` to compile the project.

Everything seems fine, but when I run `wm.exe` it doesn't arrange windows as they created.

Am I missing something here?

OS: Windows 11 26040.1000
Developer Command Prompt: Developer Command Prompt for VS 2022 Preview

This is the only warning I'm getting from the `nmake` command;

```
wm.c
wm.c(16): warning C4113: 'FARPROC' differs in parameter lists from 'HOOKPROC'
```

**Comment by nir9** [comment]
Thanks for reporting, actually haven't tried this on Win11 yet (my PC is Win10).

Perhaps it doesn't successfully place the hook? Recommend trying the new version on the master with error checking, maybe there is an error in one of the APIs.

**Comment by DemiLovato69** [comment]
I had a similar issue on Windows 11 Build 22631. With the error checking changes, I narrowed it down to the DLL not being loaded correctly, however after much debugging I found that compiling using the x64 specific compiler from VS2022 it starts to work very erratically and brings up an entirely different issue which I assume is because of my multiple monitor system.

**Comment by nir9** [comment]
@DemiRom Thanks, Fixed the README to better clarify that x64 console is needed, also improved the enum windows logic and tested with multiple monitors and it works nicely, can you check now after the fixes on Win11 if it also works good? if so I will close this

**Comment by polatengin** [comment]
I have multi-monitor, too.

I just created a Windows 11 VM on Azure, connected to it using RDP.

When I ran the `wm.exe` I'm getting this error;

![image](https://github.com/nir9/lightwm/assets/118744/bfb86a74-4543-4cea-b657-b0ae9bf56990)

Am I missing something obvious here?

_Today I'll try to create a Windows 10 VM and run the wm there 👍_

**Comment by nir9** [comment]
@polatengin That last error means the procedure is not found in the DLL exports, what do you get when running ```dumpbin /exports wm_dll.dll```, do you see ShellProc over there?

Make sure also that you are building using the Visual Studio Native Tools x64 console and Visual Studio 2022.

**Comment by DemiLovato69** [comment]
@nir9 After pulling the latest changes it "Works on my machine" 😉 

@polatengin If you change to use the x64 compiler ensure to do a complete clean by running `make clean` first. 
running `dumpbin /exports wm_dll.dll` should yield the results I have in the screenshot.

![image](https://github.com/nir9/lightwm/assets/2783997/4c082a60-cf89-4c3f-8dc1-fca9dea69ccb)

However if the `ShellProc` function name in dumpbin is something like `_ShellProc@12` it means the compiler is doing name mangling which is annoying, why MSVC is mangling names in a C project is beyond me, and why its ignoring __declspec(dllexport) is even further beyond me, almost like a bug in MSVC. 

A possible solution would be to define the exported functions in a .def file but I haven't ran into this issue since.

**Comment by polatengin** [comment]
I noticed I was using `Developer PowerShell for Visual Studio 2022 Preview` 🤦‍♂️

When I switch to `x64 Native Tools Command Prompt for Visual Studio 2022 Preview` it works on my machine, too 🥳

You can close this issue 👍

**Comment by nir9** [comment]
@DemiRom Nice thanks for the update 👍 If you stumble upon the mangling again let me know, perhaps it is a better idea to use a def file

@polatengin Thanks for updating, closing the issue
