### ISSUE TITLE
GetProcAdress won't work

### ISSUE THREAD

**Issue by theSoberSobber** [nir9/lightwm#6]
GetProcAdress won't work with just a __dllspec dllexport (because of name mangling, you'll almost certainly get hit with a 127) you need a extern C and then some flags to tell `cl` to conform to cpp standards.

**Comment by nir9** [comment]
Since the source of the project is *.c files the Visual Studio Compiler will compile the files as C and not as C++, so the name will not be mangled (you can see it compiles as C for example if you try adding a class into one of the c files - the compiler will have an error).

Also, you can see that the DLL exposes the ShellProc nicely without any mangling if you run ```dumpbin /exports wm_dll.dll```:

```
Dump of file wm_dll.dll

File Type: DLL

  Section contains the following exports for wm_dll.dll

    00000000 characteristics
    FFFFFFFF time date stamp
        0.00 version
           1 ordinal base
           1 number of functions
           1 number of names

    ordinal hint RVA      name

          1    0 00001080 ShellProc
```
